# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - gripper_controller

  gripper_controller:
    # type: FollowJointTrajectory
    # action_ns: follow_joint_trajectory
    type: GripperCommand
    joints:
      - robotiq_85_left_knuckle_joint
      # - robotiq_85_left_finger_tip_joint
      # - robotiq_85_left_inner_knuckle_joint
      # - robotiq_85_right_finger_tip_joint
      # - robotiq_85_right_inner_knuckle_joint
      # - robotiq_85_right_knuckle_joint
    action_ns: gripper_cmd
    default: true